# Site settings
title: JovemProgramador
email: jovemprogramador@designa.com.br
description: É um projeto open source criado pela Designa com objetivo de ensinar programação e preparar jovens para o mercado de trabalho.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jovemprogramador.org" # the base hostname & protocol for your site
facebook_username: jovemprog
twitter_username: jovemprog
github_username:  jovemprogramador

# Build settings
markdown: kramdown
