# Site settings
title: JovemProgramador
email: jovemprogramador@designa.com.br
description: É um projeto criado pela Designa em parceria com a iMasters com objetivo de ensinar programação para crianças e jovens a partir dos 7 anos de idade.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jovemprogramador.org" # the base hostname & protocol for your site
facebook_username: jovemprog
twitter_username: jovemprog
github_username:  jovemprogramador

# Build settings
markdown: kramdown
